config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :caja_registradoras
  resources :caja_generals
  resources :empleados
  resources :proveedores
  resources :clientes
  resources :productos
  resources :categoria
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/home', to: 'application#home' 

  root to: "caja_registradoras#index"
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :telefono, :email, :fecha_cumpleaños)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<body class="gradiente">
  <div class="py-2 text-center">  
    <%= form_with(model: cliente, local: true) do |form| %>
      <% if cliente.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

          <ul>
            <% cliente.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :nombre %>
        <%= form.text_field :nombre %>
      </div>

      <div class="field">
        <%= form.label :telefono %>
        <%= form.number_field :telefono %>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>

      <div class="field">
        <%= form.label :fecha_cumpleaños %>
        <%= form.datetime_select :fecha_cumpleaños %>
      </div>

      <div class="actions">
        <%= form.submit "guardar", class:"estilo-boton-form" %>
      </div>
    <% end %>
  </div>
</body>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Ver', @cliente, class:"links" %> 
<%= link_to 'Atras', clientes_path, class:"links" %>

app/views/clientes/index.html.erb
<body class="gradiente">
  <div class="container text-center ">

    <h1 class="py-2">Clientes</h1>

    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Telefono</th>
          <th>Email</th>
          <th>Fecha cumpleaños</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @clientes.each do |cliente| %>
          <tr>
            <td><%= cliente.nombre %></td>
            <td><%= cliente.telefono %></td>
            <td><%= cliente.email %></td>
            <td><%= cliente.fecha_cumpleaños %></td>
            <td><%= link_to 'Ver', cliente, class:"links" %></td>
            <td><%= link_to 'Editar', edit_cliente_path(cliente), class:"links" %></td>
            <td><%= link_to 'Borrar', cliente, method: :delete, data: { confirm: '¿Estas seguro?' },class:"links" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Nuevo Cliente', new_cliente_path, class:"links" %>
  </div>
</body>

app/views/clientes/new.html.erb
<h1 class="text-center py-2">New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Atras', clientes_path, class:"links" %>

app/views/clientes/show.html.erb
<body class="gradiente">
  <div class="container py-2 border-margin-vista">
    <p>
      <strong>Nombre:</strong>
      <%= @cliente.nombre %>
    </p>

    <p>
      <strong>Telefono:</strong>
      <%= @cliente.telefono %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @cliente.email %>
    </p>

    <p>
      <strong>Fecha cumpleaños:</strong>
      <%= @cliente.fecha_cumpleaños %>
    </p>

    <%= link_to 'Editar', edit_cliente_path(@cliente), class:"links" %> |
    <%= link_to 'Atras', clientes_path, class:"links" %>
  </div>

<body>