config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :caja_registradoras
  resources :caja_generals
  resources :empleados
  resources :proveedores
  resources :clientes
  resources :productos
  resources :categoria
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/home', to: 'application#home' 

  root to: "caja_registradoras#index"
end

app/models/proveedore.rb
class Proveedore < ApplicationRecord
end

app/controllers/proveedores_controller.rb
class ProveedoresController < ApplicationController
  before_action :set_proveedore, only: [:show, :edit, :update, :destroy]

  # GET /proveedores
  # GET /proveedores.json
  def index
    @proveedores = Proveedore.all
  end

  # GET /proveedores/1
  # GET /proveedores/1.json
  def show
  end

  # GET /proveedores/new
  def new
    @proveedore = Proveedore.new
  end

  # GET /proveedores/1/edit
  def edit
  end

  # POST /proveedores
  # POST /proveedores.json
  def create
    @proveedore = Proveedore.new(proveedore_params)

    respond_to do |format|
      if @proveedore.save
        format.html { redirect_to @proveedore, notice: 'Proveedore was successfully created.' }
        format.json { render :show, status: :created, location: @proveedore }
      else
        format.html { render :new }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedores/1
  # PATCH/PUT /proveedores/1.json
  def update
    respond_to do |format|
      if @proveedore.update(proveedore_params)
        format.html { redirect_to @proveedore, notice: 'Proveedore was successfully updated.' }
        format.json { render :show, status: :ok, location: @proveedore }
      else
        format.html { render :edit }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedores/1
  # DELETE /proveedores/1.json
  def destroy
    @proveedore.destroy
    respond_to do |format|
      format.html { redirect_to proveedores_url, notice: 'Proveedore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedore
      @proveedore = Proveedore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proveedore_params
      params.require(:proveedore).permit(:nombre, :telefono, :email, :nombre_empresa, :tipo_proveedor)
    end
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/views/proveedores/_form.html.erb
<%= form_with(model: proveedore, local: true) do |form| %>
  <% if proveedore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proveedore.errors.count, "error") %> prohibited this proveedore from being saved:</h2>

      <ul>
        <% proveedore.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.number_field :telefono %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :nombre_empresa %>
    <%= form.text_field :nombre_empresa %>
  </div>

  <div class="field">
    <%= form.label :tipo_proveedor %>
    <%= form.text_field :tipo_proveedor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proveedores/edit.html.erb
<h1>Editing Proveedore</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Show', @proveedore %> |
<%= link_to 'Back', proveedores_path %>

app/views/proveedores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedores</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Email</th>
      <th>Nombre empresa</th>
      <th>Tipo proveedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proveedores.each do |proveedore| %>
      <tr>
        <td><%= proveedore.nombre %></td>
        <td><%= proveedore.telefono %></td>
        <td><%= proveedore.email %></td>
        <td><%= proveedore.nombre_empresa %></td>
        <td><%= proveedore.tipo_proveedor %></td>
        <td><%= link_to 'Show', proveedore %></td>
        <td><%= link_to 'Edit', edit_proveedore_path(proveedore) %></td>
        <td><%= link_to 'Destroy', proveedore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proveedore', new_proveedore_path %>

app/views/proveedores/new.html.erb
<h1>New Proveedore</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Back', proveedores_path %>

app/views/proveedores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @proveedore.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @proveedore.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @proveedore.email %>
</p>

<p>
  <strong>Nombre empresa:</strong>
  <%= @proveedore.nombre_empresa %>
</p>

<p>
  <strong>Tipo proveedor:</strong>
  <%= @proveedore.tipo_proveedor %>
</p>

<%= link_to 'Edit', edit_proveedore_path(@proveedore) %> |
<%= link_to 'Back', proveedores_path %>