config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :caja_registradoras
  resources :caja_generals
  resources :empleados
  resources :proveedores
  resources :clientes
  resources :productos
  resources :categoria
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/home', to: 'application#home' 

  root to: "caja_registradoras#index"
end

app/models/caja_general.rb
class CajaGeneral < ApplicationRecord
end

app/controllers/caja_generals_controller.rb
class CajaGeneralsController < ApplicationController
  before_action :set_caja_general, only: [:show, :edit, :update, :destroy]

  # GET /caja_generals
  # GET /caja_generals.json
  def index
    @caja_generals = CajaGeneral.all
  end

  # GET /caja_generals/1
  # GET /caja_generals/1.json
  def show
  end

  # GET /caja_generals/new
  def new
    @caja_general = CajaGeneral.new
  end

  # GET /caja_generals/1/edit
  def edit
  end

  # POST /caja_generals
  # POST /caja_generals.json
  def create
    @caja_general = CajaGeneral.new(caja_general_params)

    respond_to do |format|
      if @caja_general.save
        format.html { redirect_to @caja_general, notice: 'Caja general was successfully created.' }
        format.json { render :show, status: :created, location: @caja_general }
      else
        format.html { render :new }
        format.json { render json: @caja_general.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caja_generals/1
  # PATCH/PUT /caja_generals/1.json
  def update
    respond_to do |format|
      if @caja_general.update(caja_general_params)
        format.html { redirect_to @caja_general, notice: 'Caja general was successfully updated.' }
        format.json { render :show, status: :ok, location: @caja_general }
      else
        format.html { render :edit }
        format.json { render json: @caja_general.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caja_generals/1
  # DELETE /caja_generals/1.json
  def destroy
    @caja_general.destroy
    respond_to do |format|
      format.html { redirect_to caja_generals_url, notice: 'Caja general was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caja_general
      @caja_general = CajaGeneral.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caja_general_params
      params.require(:caja_general).permit(:tipo, :entrada, :salida, :descripcion, :fecha)
    end
end

app/helpers/caja_generals_helper.rb
module CajaGeneralsHelper
end

app/views/caja_generals/_form.html.erb
<body class="gradiente">
  <div class="py-2 text-center">
    <%= form_with(model: caja_general, local: true) do |form| %>
      <% if caja_general.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(caja_general.errors.count, "error") %> prohibited this caja_general from being saved:</h2>

          <ul>
            <% caja_general.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :tipo %>
        <%= form.text_field :tipo %>
      </div>

      <div class="field">
        <%= form.label :entrada %>
        <%= form.text_field :entrada %>
      </div>

      <div class="field">
        <%= form.label :salida %>
        <%= form.text_field :salida %>
      </div>

      <div class="field">
        <%= form.label :descripcion %>
        <%= form.text_field :descripcion %>
      </div>

      <div class="field">
        <%= form.label :fecha %>
        <%= form.datetime_select :fecha %>
      </div>

      <div class="actions">
        <%= form.submit "Guardar", class:"estilo-boton-form" %>
      </div>
    <% end %>
  </div>  
</div>

app/views/caja_generals/edit.html.erb
<div class="gradiente">
    <h1 class="text-center py-2">Editar Caja General</h1>

    <%= render 'form', caja_general: @caja_general %>

    <%= link_to 'Ver', @caja_general, class:"links" %> 
    <%= link_to 'Atras', caja_generals_path, class:"links" %>
</div>

app/views/caja_generals/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<body class="gradiente">
  <div class="container text-center">
    <h1 class="py-2">Caja General</h1>

    <table>
      <thead>
        <tr>
          <th>Tipo</th>
          <th>Entrada</th>
          <th>Salida</th>
          <th>Descripcion</th>
          <th>Fecha</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @caja_generals.each do |caja_general| %>
          <tr>
            <td><%= caja_general.tipo %></td>
            <td><%= caja_general.entrada %></td>
            <td><%= caja_general.salida %></td>
            <td><%= caja_general.descripcion %></td>
            <td><%= caja_general.fecha %></td>
            <td><%= link_to 'Ver', caja_general, class:"links" %></td>
            <td><%= link_to 'Editar', edit_caja_general_path(caja_general), class:"links" %></td>
            <td><%= link_to 'Borrar', caja_general, method: :delete, data: { confirm: '¿Estas seguro?' }, class:"links" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Crear Registro', new_caja_general_path, class:"links" %>
  </div>
</body>

app/views/caja_generals/new.html.erb
<h1 class="text-center py-2">Nuevo registro de Caja General</h1>

<%= render 'form', caja_general: @caja_general %>

<%= link_to 'Atras', caja_generals_path, class:"links" %>

app/views/caja_generals/show.html.erb
<body class="gradiente">
  <div class="container py-2 border-margin-vista"> 
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Tipo:</strong>
      <%= @caja_general.tipo %>
    </p>

    <p>
      <strong>Entrada:</strong>
      <%= @caja_general.entrada %>
    </p>

    <p>
      <strong>Salida:</strong>
      <%= @caja_general.salida %>
    </p>

    <p>
      <strong>Descripcion:</strong>
      <%= @caja_general.descripcion %>
    </p>

    <p>
      <strong>Fecha:</strong>
      <%= @caja_general.fecha %>
    </p>


    <%= link_to 'Editar', edit_caja_general_path(@caja_general), class:"links" %> 
    <%= link_to 'Atras',  caja_generals_path, class:"links" %>

  </div>
</body>